[package]
edition = "2024"
name = "rounds_again"
version = "0.1.0"

[dependencies]
arrayvec = "0.7.8"
bevy = { version = "0.19.1", default-features = true, features = [
    "debug",
    "dynamic_linking",
    "wayland",
] }
bevy_mod_debugdump = "0.16.0"
bevy_rapier2d = { version = "0.36.0", features = ["debug-render-2d"] }
parry2d = "0.30.2-glamx0.2-b"
rand = "0.10.2"
serde = { version = "1.0.229", features = ["derive"] }
toml = "1.1.6"

[lints.clippy]
type_complexity = "allow"

[profile.release]
codegen-units = 1

[profile.dev.package."*"]
opt-level = 3
